# ----------------------------------------------------- 
# Window rules (New Syntax)
# ----------------------------------------------------- 

windowrule = match:class ^(pavucontrol)$
windowrule = match:class ^(blueman-manager)$
windowrule = match:class ^(nm-connection-editor)$
windowrule = match:class ^(nemo)$, opacity 0.9
windowrule = match:class ^(Alacritty)$, opacity 0.8 0.8

# Browser Picture in Picture
windowrule = match:title ^(Picture-in-Picture)$
windowrule = match:title ^(Picture-in-Picture)$
windowrule = match:title ^(Picture-in-Picture)$, move 69.5% 4%
